var autoUrl = "https://{0}/search?source=auto&query={1}"
var forceUrl = "{0}/search?source=auto&query={1}"


function getword(info, tab) {
    chrome.storage.sync.get(["targetLang"], (targetItems) => {
        chrome.storage.sync.get(["sourceLang"], (items) => {
            const mapKey = domainMap[targetItems.targetLang].short + "-" + domainMap[items.sourceLang].short;

            if (items.sourceLang === "Auto" || !(mapKey in langMaps)) {
                chrome.tabs.create({
                    url: autoUrl.format(domainMap[targetItems.targetLang].url, info.selectionText)
                });
            }
            else {
                if (mapKey in langMaps) {
                    chrome.tabs.create({
                        url: forceUrl.format(
                            langMaps[mapKey],
                            info.selectionText
                        )
                    });
                }
            }
        });
    })
}

chrome.contextMenus.create({
    title: "Linguee: \"%s\"",
    contexts: ["selection"],
    onclick: getword,
});

if (!String.prototype.format) {
    String.prototype.format = function () {
        var args = arguments;
        return this.replace(/{(\d+)}/g, function (match, number) {
            return typeof args[number] != 'undefined'
                ? args[number]
                : match
                ;
        });
    };
}

const domainMap = {
    "English": { url: "www.linguee.com", short: "EN" },
    "German": { url: "www.linguee.de", short: "DE" },
    "French": { url: "www.linguee.fr", short: "FR" },
    "Spanish": { url: "www.linguee.es", short: "ES" },
    "Chinese": { url: "cn.linguee.com", short: "ZH" },
    "Russian": { url: "www.linguee.ru", short: "RU" },
    "Japanese": { url: "www.linguee.jp", short: "JA" },
    "Portuguese": { url: "www.linguee.pt", short: "PT" },
    "Italian": { url: "www.linguee.it", short: "IT" },
    "Dutch": { url: "www.linguee.nl", short: "NL" },
    "Polish": { url: "www.linguee.pl", short: "PL" },
    "Swedish": { url: "www.linguee.se", short: "SV" },
    "Danish": { url: "www.linguee.dk", short: "DA" },
    "Finnish": { url: "fi.linguee.com", short: "FI" },
    "Greek": { url: "www.linguee.gr", short: "EL" },
    "Czech": { url: "www.linguee.cz", short: "CS" },
    "Romanian": { url: "ro.linguee.com", short: "RO" },
    "Hungarian": { url: "www.linguee.hu", short: "HU" },
    "Slovak": { url: "sk.linguee.com", short: "SK" },
    "Bulgarian": { url: "bg.linguee.com", short: "BG" },
    "Slovene": { url: "sl.linguee.com", short: "SL" },
    "Lithuanian": { url: "lt.linguee.com", short: "LT" },
    "Latvian": { url: "lv.linguee.com", short: "LV" },
    "Estonian": { url: "et.linguee.com", short: "ET" },
    "Maltese": { url: "mt.linguee.com", short: "MT" }
}


const langMaps = {
    "BG-CS": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%87%D0%B5%D1%88%D0%BA%D0%B8",
    "BG-DA": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B4%D0%B0%D1%82%D1%81%D0%BA%D0%B8",
    "BG-DE": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BD%D0%B5%D0%BC%D1%81%D0%BA%D0%B8",
    "BG-EL": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B3%D1%80%D1%8A%D1%86%D0%BA%D0%B8",
    "BG-EN": "https://www.linguee.com/bulgarian-english",
    "BG-ES": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B8%D1%81%D0%BF%D0%B0%D0%BD%D1%81%D0%BA%D0%B8",
    "BG-ET": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B5%D1%81%D1%82%D0%BE%D0%BD%D1%81%D0%BA%D0%B8",
    "BG-FI": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%84%D0%B8%D0%BD%D1%81%D0%BA%D0%B8",
    "BG-FR": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%84%D1%80%D0%B5%D0%BD%D1%81%D0%BA%D0%B8",
    "BG-HU": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%83%D0%BD%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8",
    "BG-IT": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%B8%D1%82%D0%B0%D0%BB%D0%B8%D0%B0%D0%BD%D1%81%D0%BA%D0%B8",
    "BG-LT": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BB%D0%B8%D1%82%D0%BE%D0%B2%D1%81%D0%BA%D0%B8",
    "BG-LV": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BB%D0%B0%D1%82%D0%B2%D0%B8%D0%B9%D1%81%D0%BA%D0%B8",
    "BG-MT": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BC%D0%B0%D0%BB%D1%82%D0%B8%D0%B9%D1%81%D0%BA%D0%B8",
    "BG-NL": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%85%D0%BE%D0%BB%D0%B0%D0%BD%D0%B4%D1%81%D0%BA%D0%B8",
    "BG-PL": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BB%D0%B0%D0%BA",
    "BG-PT": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D0%BF%D0%BE%D1%80%D1%82%D1%83%D0%B3%D0%B0%D0%BB%D1%81%D0%BA%D0%B8",
    "BG-RO": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%80%D1%83%D0%BC%D1%8A%D0%BD%D1%81%D0%BA%D0%B8",
    "BG-SK": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%88%D0%BA%D0%B8",
    "BG-SL": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%81%D0%BB%D0%BE%D0%B2%D0%B5%D0%BD%D1%81%D0%BA%D0%B8",
    "BG-SV": "https://bg.linguee.com/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-%D1%88%D0%B2%D0%B5%D0%B4%D1%81%D0%BA%D0%B8",
    "CS-BG": "https://www.linguee.cz/%C4%8De%C5%A1tina-bulhar%C5%A1tina",
    "CS-DA": "https://www.linguee.cz/%C4%8De%C5%A1tina-d%C3%A1n%C5%A1tina",
    "CS-DE": "https://www.linguee.cz/%C4%8De%C5%A1tina-n%C4%9Bm%C4%8Dina",
    "CS-EL": "https://www.linguee.cz/%C4%8De%C5%A1tina-%C5%99e%C4%8Dtina",
    "CS-EN": "https://www.linguee.com/czech-english",
    "CS-ES": "https://www.linguee.cz/%C4%8De%C5%A1tina-%C5%A1pan%C4%9Bl%C5%A1tina",
    "CS-ET": "https://www.linguee.cz/%C4%8De%C5%A1tina-eston%C5%A1tina",
    "CS-FI": "https://www.linguee.cz/%C4%8De%C5%A1tina-fin%C5%A1tina",
    "CS-FR": "https://www.linguee.cz/%C4%8De%C5%A1tina-francouz%C5%A1tina",
    "CS-HU": "https://www.linguee.cz/%C4%8De%C5%A1tina-ma%C4%8Far%C5%A1tina",
    "CS-IT": "https://www.linguee.cz/%C4%8De%C5%A1tina-ital%C5%A1tina",
    "CS-LT": "https://www.linguee.cz/%C4%8De%C5%A1tina-litev%C5%A1tina",
    "CS-LV": "https://www.linguee.cz/%C4%8De%C5%A1tina-loty%C5%A1tina",
    "CS-MT": "https://www.linguee.cz/%C4%8De%C5%A1tina-malt%C5%A1tina",
    "CS-NL": "https://www.linguee.cz/%C4%8De%C5%A1tina-holand%C5%A1tina",
    "CS-PL": "https://www.linguee.cz/%C4%8De%C5%A1tina-pol%C5%A1tina",
    "CS-PT": "https://www.linguee.cz/%C4%8De%C5%A1tina-portugal%C5%A1tina",
    "CS-RO": "https://www.linguee.cz/%C4%8De%C5%A1tina-rumun%C5%A1tina",
    "CS-SK": "https://www.linguee.cz/%C4%8De%C5%A1tina-sloven%C5%A1tina",
    "CS-SL": "https://www.linguee.cz/%C4%8De%C5%A1tina-slovin%C5%A1tina",
    "CS-SV": "https://www.linguee.cz/%C4%8De%C5%A1tina-%C5%A1v%C3%A9d%C5%A1tina",
    "DA-BG": "https://www.linguee.dk/dansk-bulgarsk",
    "DA-CS": "https://www.linguee.dk/dansk-tjekkisk",
    "DA-DE": "https://www.linguee.dk/dansk-tysk",
    "DA-EL": "https://www.linguee.dk/dansk-gr%C3%A6sk",
    "DA-EN": "https://www.linguee.com/danish-english",
    "DA-ES": "https://www.linguee.dk/dansk-spansk",
    "DA-ET": "https://www.linguee.dk/dansk-estisk",
    "DA-FI": "https://www.linguee.dk/dansk-finsk",
    "DA-FR": "https://www.linguee.dk/dansk-fransk",
    "DA-HU": "https://www.linguee.dk/dansk-ungarsk",
    "DA-IT": "https://www.linguee.dk/dansk-italiensk",
    "DA-LT": "https://www.linguee.dk/dansk-litauisk",
    "DA-LV": "https://www.linguee.dk/dansk-letlandsk",
    "DA-MT": "https://www.linguee.dk/dansk-maltesisk",
    "DA-NL": "https://www.linguee.dk/dansk-hollandsk",
    "DA-PL": "https://www.linguee.dk/dansk-polik",
    "DA-PT": "https://www.linguee.dk/dansk-portugisisk",
    "DA-RO": "https://www.linguee.dk/dansk-rum%C3%A6nsk",
    "DA-SK": "https://www.linguee.dk/dansk-slovakisk",
    "DA-SL": "https://www.linguee.dk/dansk-slovensk",
    "DA-SV": "https://www.linguee.dk/dansk-svensk",
    "DE-BG": "https://www.linguee.de/deutsch-bulgarisch",
    "DE-CS": "https://www.linguee.de/deutsch-tschechisch",
    "DE-DA": "https://www.linguee.de/deutsch-d%C3%A4nisch",
    "DE-EL": "https://www.linguee.de/deutsch-griechisch",
    "DE-EN": "https://www.linguee.com/german-english",
    "DE-ES": "https://www.linguee.de/deutsch-spanisch",
    "DE-ET": "https://www.linguee.de/deutsch-estnisch",
    "DE-FI": "https://www.linguee.de/deutsch-finnisch",
    "DE-FR": "https://www.linguee.de/deutsch-franzoesisch",
    "DE-HU": "https://www.linguee.de/deutsch-ungarisch",
    "DE-IT": "https://www.linguee.de/deutsch-italienisch",
    "DE-LT": "https://www.linguee.de/deutsch-litauisch",
    "DE-LV": "https://www.linguee.de/deutsch-lettisch",
    "DE-MT": "https://www.linguee.de/deutsch-maltesisch",
    "DE-NL": "https://www.linguee.de/deutsch-niederl%C3%A4ndisch",
    "DE-PL": "https://www.linguee.de/deutsch-polnisch",
    "DE-PT": "https://www.linguee.de/deutsch-portugiesisch",
    "DE-RO": "https://www.linguee.de/deutsch-rum%C3%A4nisch",
    "DE-SK": "https://www.linguee.de/deutsch-slowakisch",
    "DE-SL": "https://www.linguee.de/deutsch-slowenisch",
    "DE-SV": "https://www.linguee.de/deutsch-schwedisch",
    "EL-BG": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B2%CE%BF%CF%85%CE%BB%CE%B3%CE%AC%CF%81%CE%B9%CE%BA%CE%B1",
    "EL-CS": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%84%CF%83%CE%B5%CF%87%CE%B9%CE%BA%CE%AC",
    "EL-DA": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B4%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC",
    "EL-DE": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B3%CE%B5%CF%81%CE%BC%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC",
    "EL-EN": "https://www.linguee.com/greek-english",
    "EL-ES": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B9%CF%83%CF%80%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC",
    "EL-ET": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B5%CF%83%CE%B8%CE%BF%CE%BD%CE%B9%CE%BA%CE%AC",
    "EL-FI": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%86%CE%B9%CE%BD%CE%BB%CE%B1%CE%BD%CE%B4%CE%B9%CE%BA%CE%AC",
    "EL-FR": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B3%CE%B1%CE%BB%CE%BB%CE%B9%CE%BA%CE%AC",
    "EL-HU": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BF%CF%85%CE%B3%CE%B3%CF%81%CE%B9%CE%BA%CE%AC",
    "EL-IT": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%B9%CF%84%CE%B1%CE%BB%CE%B9%CE%BA%CE%AC",
    "EL-LT": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BB%CE%B9%CE%B8%CE%BF%CF%85%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC",
    "EL-LV": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BB%CE%B5%CF%84%CE%BF%CE%BD%CE%B9%CE%BA%CE%AC",
    "EL-MT": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BC%CE%B1%CE%BB%CF%84%CE%AD%CE%B6%CE%B9%CE%BA%CE%B1",
    "EL-NL": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CE%BF%CE%BB%CE%BB%CE%B1%CE%BD%CE%B4%CE%B9%CE%BA%CE%AC",
    "EL-PL": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%80%CE%BF%CE%BB%CF%89%CE%BD%CE%B9%CE%BA%CE%AC",
    "EL-PT": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%80%CE%BF%CF%81%CF%84%CE%BF%CE%B3%CE%B1%CE%BB%CE%B9%CE%BA%CE%AC",
    "EL-RO": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%81%CE%BF%CF%85%CE%BC%CE%B1%CE%BD%CE%B9%CE%BA%CE%AC",
    "EL-SK": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%83%CE%BB%CE%BF%CE%B2%CE%AC%CE%BA%CE%B9%CE%BA%CE%B1",
    "EL-SL": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%83%CE%BB%CE%BF%CE%B2%CE%AD%CE%BD%CE%B9%CE%BA%CE%B1",
    "EL-SV": "https://www.linguee.gr/%CE%B5%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC-%CF%83%CE%BF%CF%85%CE%B7%CE%B4%CE%B9%CE%BA%CE%AC",
    "EN-BG": "https://www.linguee.com/english-bulgarian",
    "EN-CS": "https://www.linguee.com/english-czech",
    "EN-DA": "https://www.linguee.com/english-danish",
    "EN-DE": "https://www.linguee.com/english-german",
    "EN-EL": "https://www.linguee.com/english-greek",
    "EN-ES": "https://www.linguee.com/english-spanish",
    "EN-ET": "https://www.linguee.com/english-estonian",
    "EN-FI": "https://www.linguee.com/english-finnish",
    "EN-FR": "https://www.linguee.com/english-french",
    "EN-HU": "https://www.linguee.com/english-hungarian",
    "EN-IT": "https://www.linguee.com/english-italian",
    "EN-JA": "https://www.linguee.com/english-japanese",
    "EN-LT": "https://www.linguee.com/english-lithuanian",
    "EN-LV": "https://www.linguee.com/english-latvian",
    "EN-MT": "https://www.linguee.com/english-maltese",
    "EN-NL": "https://www.linguee.com/english-dutch",
    "EN-PL": "https://www.linguee.com/english-polish",
    "EN-PT": "https://www.linguee.com/english-portuguese",
    "EN-RO": "https://www.linguee.com/english-romanian",
    "EN-RU": "https://www.linguee.com/english-russian",
    "EN-SK": "https://www.linguee.com/english-slovak",
    "EN-SL": "https://www.linguee.com/english-slovene",
    "EN-SV": "https://www.linguee.com/english-swedish",
    "EN-ZH": "https://www.linguee.com/english-chinese",
    "ES-BG": "https://www.linguee.es/espanol-bulgaro",
    "ES-CS": "https://www.linguee.es/espanol-checo",
    "ES-DA": "https://www.linguee.es/espanol-danes",
    "ES-DE": "https://www.linguee.es/espanol-aleman",
    "ES-EL": "https://www.linguee.es/espanol-griego",
    "ES-EN": "https://www.linguee.com/spanish-english",
    "ES-ET": "https://www.linguee.es/espanol-estonio",
    "ES-FI": "https://www.linguee.es/espanol-fines",
    "ES-FR": "https://www.linguee.es/espanol-frances",
    "ES-HU": "https://www.linguee.es/espanol-hungaro",
    "ES-IT": "https://www.linguee.es/espanol-italiano",
    "ES-LT": "https://www.linguee.es/espanol-lituano",
    "ES-LV": "https://www.linguee.es/espanol-leton",
    "ES-MT": "https://www.linguee.es/espanol-maltes",
    "ES-NL": "https://www.linguee.es/espanol-neerlandes",
    "ES-PL": "https://www.linguee.es/espanol-polaco",
    "ES-PT": "https://www.linguee.es/espanol-portugues",
    "ES-RO": "https://www.linguee.es/espanol-rumano",
    "ES-SK": "https://www.linguee.es/espanol-eslovaco",
    "ES-SL": "https://www.linguee.es/espanol-esloveno",
    "ES-SV": "https://www.linguee.es/espanol-sueco",
    "ET-BG": "https://et.linguee.com/eesti-bulgaaria",
    "ET-CS": "https://et.linguee.com/eesti-t%C5%A1ehhi",
    "ET-DA": "https://et.linguee.com/eesti-taani",
    "ET-DE": "https://et.linguee.com/eesti-saksa",
    "ET-EL": "https://et.linguee.com/eesti-kreeka",
    "ET-EN": "https://www.linguee.com/estonian-english",
    "ET-ES": "https://et.linguee.com/eesti-hispaania",
    "ET-FI": "https://et.linguee.com/eesti-soome",
    "ET-FR": "https://et.linguee.com/eesti-prantsuse",
    "ET-HU": "https://et.linguee.com/eesti-ungari",
    "ET-IT": "https://et.linguee.com/eesti-itaalia",
    "ET-LT": "https://et.linguee.com/eesti-leedu",
    "ET-LV": "https://et.linguee.com/eesti-l%C3%A4ti",
    "ET-MT": "https://et.linguee.com/eesti-malta",
    "ET-NL": "https://et.linguee.com/eesti-hollandi",
    "ET-PL": "https://et.linguee.com/eesti-poola",
    "ET-PT": "https://et.linguee.com/eesti-portugali",
    "ET-RO": "https://et.linguee.com/eesti-rumeenia",
    "ET-SK": "https://et.linguee.com/eesti-slovaki",
    "ET-SL": "https://et.linguee.com/eesti-sloveeni",
    "ET-SV": "https://et.linguee.com/eesti-rootsi",
    "FI-BG": "https://fi.linguee.com/suomi-bulgaria",
    "FI-CS": "https://fi.linguee.com/suomi-t%C5%A1ekki",
    "FI-DA": "https://fi.linguee.com/suomi-tanska",
    "FI-DE": "https://fi.linguee.com/suomi-saksa",
    "FI-EL": "https://fi.linguee.com/suomi-kreikka",
    "FI-EN": "https://www.linguee.com/finnish-english",
    "FI-ES": "https://fi.linguee.com/suomi-espanja",
    "FI-ET": "https://fi.linguee.com/suomi-viro",
    "FI-FR": "https://fi.linguee.com/suomi-ranska",
    "FI-HU": "https://fi.linguee.com/suomi-unkari",
    "FI-IT": "https://fi.linguee.com/suomi-italia",
    "FI-LT": "https://fi.linguee.com/suomi-liettua",
    "FI-LV": "https://fi.linguee.com/suomi-latvia",
    "FI-MT": "https://fi.linguee.com/suomi-malta",
    "FI-NL": "https://fi.linguee.com/suomi-hollanti",
    "FI-PL": "https://fi.linguee.com/suomi-puola",
    "FI-PT": "https://fi.linguee.com/suomi-portugali",
    "FI-RO": "https://fi.linguee.com/suomi-romania",
    "FI-SK": "https://fi.linguee.com/suomi-slovakki",
    "FI-SL": "https://fi.linguee.com/suomi-slovenia",
    "FI-SV": "https://fi.linguee.com/suomi-ruotsi",
    "FR-BG": "https://www.linguee.fr/francais-bulgare",
    "FR-CS": "https://www.linguee.fr/francais-tcheque",
    "FR-DA": "https://www.linguee.fr/francais-danois",
    "FR-DE": "https://www.linguee.fr/francais-allemand",
    "FR-EL": "https://www.linguee.fr/francais-grec",
    "FR-EN": "https://www.linguee.com/french-english",
    "FR-ES": "https://www.linguee.fr/francais-espagnol",
    "FR-ET": "https://www.linguee.fr/francais-estonien",
    "FR-FI": "https://www.linguee.fr/francais-finnois",
    "FR-HU": "https://www.linguee.fr/francais-hongrois",
    "FR-IT": "https://www.linguee.fr/francais-italien",
    "FR-LT": "https://www.linguee.fr/francais-lituanien",
    "FR-LV": "https://www.linguee.fr/francais-letton",
    "FR-MT": "https://www.linguee.fr/francais-maltais",
    "FR-NL": "https://www.linguee.fr/francais-neerlandais",
    "FR-PL": "https://www.linguee.fr/francais-polonais",
    "FR-PT": "https://www.linguee.fr/francais-portugais",
    "FR-RO": "https://www.linguee.fr/francais-roumain",
    "FR-SK": "https://www.linguee.fr/francais-slovaque",
    "FR-SL": "https://www.linguee.fr/francais-slovene",
    "FR-SV": "https://www.linguee.fr/francais-suedois",
    "HU-BG": "https://www.linguee.hu/magyar-bolg%C3%A1r",
    "HU-CS": "https://www.linguee.hu/magyar-cseh",
    "HU-DA": "https://www.linguee.hu/magyar-d%C3%A1n",
    "HU-DE": "https://www.linguee.hu/magyar-n%C3%A9met",
    "HU-EL": "https://www.linguee.hu/magyar-g%C3%B6r%C3%B6g",
    "HU-EN": "https://www.linguee.com/hungarian-english",
    "HU-ES": "https://www.linguee.hu/magyar-spanyol",
    "HU-ET": "https://www.linguee.hu/magyar-%C3%A9szt",
    "HU-FI": "https://www.linguee.hu/magyar-finn",
    "HU-FR": "https://www.linguee.hu/magyar-francia",
    "HU-IT": "https://www.linguee.hu/magyar-olasz",
    "HU-LT": "https://www.linguee.hu/magyar-litv%C3%A1n",
    "HU-LV": "https://www.linguee.hu/magyar-lett",
    "HU-MT": "https://www.linguee.hu/magyar-m%C3%A1ltai",
    "HU-NL": "https://www.linguee.hu/magyar-holland",
    "HU-PL": "https://www.linguee.hu/magyar-lengyel",
    "HU-PT": "https://www.linguee.hu/magyar-portug%C3%A1l",
    "HU-RO": "https://www.linguee.hu/magyar-rom%C3%A1n",
    "HU-SK": "https://www.linguee.hu/magyar-szlov%C3%A1k",
    "HU-SL": "https://www.linguee.hu/magyar-szlov%C3%A9n",
    "HU-SV": "https://www.linguee.hu/magyar-sv%C3%A9d",
    "IT-BG": "https://www.linguee.it/italiano-bulgaro",
    "IT-CS": "https://www.linguee.it/italiano-ceco",
    "IT-DA": "https://www.linguee.it/italiano-danese",
    "IT-DE": "https://www.linguee.it/italiano-tedesco",
    "IT-EL": "https://www.linguee.it/italiano-greco",
    "IT-EN": "https://www.linguee.com/italian-english",
    "IT-ES": "https://www.linguee.it/italiano-spagnolo",
    "IT-ET": "https://www.linguee.it/italiano-estone",
    "IT-FI": "https://www.linguee.it/italiano-finlandese",
    "IT-FR": "https://www.linguee.it/italiano-francese",
    "IT-HU": "https://www.linguee.it/italiano-ungherese",
    "IT-LT": "https://www.linguee.it/italiano-lituano",
    "IT-LV": "https://www.linguee.it/italiano-lettone",
    "IT-MT": "https://www.linguee.it/italiano-maltese",
    "IT-NL": "https://www.linguee.it/italiano-olandese",
    "IT-PL": "https://www.linguee.it/italiano-polacco",
    "IT-PT": "https://www.linguee.it/italiano-portoghese",
    "IT-RO": "https://www.linguee.it/italiano-rumeno",
    "IT-SK": "https://www.linguee.it/italiano-slovacco",
    "IT-SL": "https://www.linguee.it/italiano-sloveno",
    "IT-SV": "https://www.linguee.it/italiano-svedese",
    "JA-EN": "https://www.linguee.com/japanese-english",
    "LT-BG": "https://lt.linguee.com/lietuvi%C5%B3-bulgar%C5%B3",
    "LT-CS": "https://lt.linguee.com/lietuvi%C5%B3-%C4%8Dek%C5%B3",
    "LT-DA": "https://lt.linguee.com/lietuvi%C5%B3-dan%C5%B3",
    "LT-DE": "https://lt.linguee.com/lietuvi%C5%B3-vokie%C4%8Di%C5%B3",
    "LT-EL": "https://lt.linguee.com/lietuvi%C5%B3-graik%C5%B3",
    "LT-EN": "https://www.linguee.com/lithuanian-english",
    "LT-ES": "https://lt.linguee.com/lietuvi%C5%B3-ispan%C5%B3",
    "LT-ET": "https://lt.linguee.com/lietuvi%C5%B3-est%C5%B3",
    "LT-FI": "https://lt.linguee.com/lietuvi%C5%B3-suomi%C5%B3",
    "LT-FR": "https://lt.linguee.com/lietuvi%C5%B3-pranc%C5%ABz%C5%B3",
    "LT-HU": "https://lt.linguee.com/lietuvi%C5%B3-vengr%C5%B3",
    "LT-IT": "https://lt.linguee.com/lietuvi%C5%B3-ital%C5%B3",
    "LT-LV": "https://lt.linguee.com/lietuvi%C5%B3-latvi%C5%B3",
    "LT-MT": "https://lt.linguee.com/lietuvi%C5%B3-maltie%C4%8Di%C5%B3",
    "LT-NL": "https://lt.linguee.com/lietuvi%C5%B3-oland%C5%B3",
    "LT-PL": "https://lt.linguee.com/lietuvi%C5%B3-lenk%C5%B3",
    "LT-PT": "https://lt.linguee.com/lietuvi%C5%B3-portugal%C5%B3",
    "LT-RO": "https://lt.linguee.com/lietuvi%C5%B3-rumun%C5%B3",
    "LT-SK": "https://lt.linguee.com/lietuvi%C5%B3-slovak%C5%B3",
    "LT-SL": "https://lt.linguee.com/lietuvi%C5%B3-slov%C4%97n%C5%B3",
    "LT-SV": "https://lt.linguee.com/lietuvi%C5%B3-%C5%A1ved%C5%B3",
    "LV-BG": "https://lv.linguee.com/latvie%C5%A1u-bulg%C4%81ru",
    "LV-CS": "https://lv.linguee.com/latvie%C5%A1u-%C4%8Dehu",
    "LV-DA": "https://lv.linguee.com/latvie%C5%A1u-d%C4%81%C5%86u",
    "LV-DE": "https://lv.linguee.com/latvie%C5%A1u-v%C4%81cu",
    "LV-EL": "https://lv.linguee.com/latvie%C5%A1u-grie%C4%B7u",
    "LV-EN": "https://www.linguee.com/latvian-english",
    "LV-ES": "https://lv.linguee.com/latvie%C5%A1u-sp%C4%81%C5%86u",
    "LV-ET": "https://lv.linguee.com/latvie%C5%A1u-igau%C5%86u",
    "LV-FI": "https://lv.linguee.com/latvie%C5%A1u-somu",
    "LV-FR": "https://lv.linguee.com/latvie%C5%A1u-fran%C4%8Du",
    "LV-HU": "https://lv.linguee.com/latvie%C5%A1u-ung%C4%81ru",
    "LV-IT": "https://lv.linguee.com/latvie%C5%A1u-it%C4%81%C4%BCu",
    "LV-LT": "https://lv.linguee.com/latvie%C5%A1u-lietuvie%C5%A1u",
    "LV-MT": "https://lv.linguee.com/latvie%C5%A1u-maltie%C5%A1u",
    "LV-NL": "https://lv.linguee.com/latvie%C5%A1u-holandie%C5%A1u",
    "LV-PL": "https://lv.linguee.com/latvie%C5%A1u-po%C4%BCu",
    "LV-PT": "https://lv.linguee.com/latvie%C5%A1u-portug%C4%81%C4%BCu",
    "LV-RO": "https://lv.linguee.com/latvie%C5%A1u-rum%C4%81%C5%86u",
    "LV-SK": "https://lv.linguee.com/latvie%C5%A1u-slov%C4%81ku",
    "LV-SL": "https://lv.linguee.com/latvie%C5%A1u-slov%C4%93%C5%86u",
    "LV-SV": "https://lv.linguee.com/latvie%C5%A1u-zviedru",
    "MT-BG": "https://mt.linguee.com/malti-bulgaru",
    "MT-CS": "https://mt.linguee.com/malti-%C4%8Bek",
    "MT-DA": "https://mt.linguee.com/malti-dani%C5%BC+",
    "MT-DE": "https://mt.linguee.com/malti-%C4%A1ermani%C5%BC",
    "MT-EL": "https://mt.linguee.com/malti-grieg",
    "MT-EN": "https://www.linguee.com/maltese-english",
    "MT-ES": "https://mt.linguee.com/malti-spanjol",
    "MT-ET": "https://mt.linguee.com/malti-estonjan",
    "MT-FI": "https://mt.linguee.com/malti-finlandi%C5%BC+",
    "MT-FR": "https://mt.linguee.com/malti-fran%C4%8Bi%C5%BC",
    "MT-HU": "https://mt.linguee.com/malti-ungeri%C5%BC",
    "MT-IT": "https://mt.linguee.com/malti-taljan",
    "MT-LT": "https://mt.linguee.com/malti-litwan",
    "MT-LV": "https://mt.linguee.com/malti-latvjan",
    "MT-NL": "https://mt.linguee.com/malti-olandi%C5%BC",
    "MT-PL": "https://mt.linguee.com/malti-pollakk",
    "MT-PT": "https://mt.linguee.com/malti-portugi%C5%BC+",
    "MT-RO": "https://mt.linguee.com/malti-rumen",
    "MT-SK": "https://mt.linguee.com/malti-slovakk",
    "MT-SL": "https://mt.linguee.com/malti-sloven",
    "MT-SV": "https://mt.linguee.com/malti-svedi%C5%BC",
    "NL-BG": "https://www.linguee.nl/nederlands-bulgaars",
    "NL-CS": "https://www.linguee.nl/nederlands-tsjechisch",
    "NL-DA": "https://www.linguee.nl/nederlands-deens",
    "NL-DE": "https://www.linguee.nl/nederlands-duits",
    "NL-EL": "https://www.linguee.nl/nederlands-grieks",
    "NL-EN": "https://www.linguee.com/dutch-english",
    "NL-ES": "https://www.linguee.nl/nederlands-spaans",
    "NL-ET": "https://www.linguee.nl/nederlands-ests",
    "NL-FI": "https://www.linguee.nl/nederlands-fins",
    "NL-FR": "https://www.linguee.nl/nederlands-frans",
    "NL-HU": "https://www.linguee.nl/nederlands-hongaars",
    "NL-IT": "https://www.linguee.nl/nederlands-italiaans",
    "NL-LT": "https://www.linguee.nl/nederlands-litouws",
    "NL-LV": "https://www.linguee.nl/nederlands-lets",
    "NL-MT": "https://www.linguee.nl/nederlands-maltees",
    "NL-PL": "https://www.linguee.nl/nederlands-pools",
    "NL-PT": "https://www.linguee.nl/nederlands-portugees",
    "NL-RO": "https://www.linguee.nl/nederlands-roemeens",
    "NL-SK": "https://www.linguee.nl/nederlands-slowaaks",
    "NL-SL": "https://www.linguee.nl/nederlands-sloveens",
    "NL-SV": "https://www.linguee.nl/nederlands-zweeds",
    "PL-BG": "https://www.linguee.pl/polski-bu%C5%82garski",
    "PL-CS": "https://www.linguee.pl/polski-czeski",
    "PL-DA": "https://www.linguee.pl/polski-du%C5%84ski",
    "PL-DE": "https://www.linguee.pl/polski-niemiecki",
    "PL-EL": "https://www.linguee.pl/polski-grecki",
    "PL-EN": "https://www.linguee.com/polish-english",
    "PL-ES": "https://www.linguee.pl/polski-hiszpa%C5%84ski",
    "PL-ET": "https://www.linguee.pl/polski-esto%C5%84ski",
    "PL-FI": "https://www.linguee.pl/polski-fi%C5%84ski",
    "PL-FR": "https://www.linguee.pl/polski-francuski",
    "PL-HU": "https://www.linguee.pl/polski-w%C4%99gierski",
    "PL-IT": "https://www.linguee.pl/polski-w%C5%82oski",
    "PL-LT": "https://www.linguee.pl/polski-litewski",
    "PL-LV": "https://www.linguee.pl/polski-%C5%82otewski",
    "PL-MT": "https://www.linguee.pl/polski-malta%C5%84ski",
    "PL-NL": "https://www.linguee.pl/polski-holenderski",
    "PL-PT": "https://www.linguee.pl/polski-portugalski",
    "PL-RO": "https://www.linguee.pl/polski-rumu%C5%84ski",
    "PL-SK": "https://www.linguee.pl/polski-s%C5%82owacki",
    "PL-SL": "https://www.linguee.pl/polski-s%C5%82owe%C5%84ski",
    "PL-SV": "https://www.linguee.pl/polski-szwedzki",
    "PT-BG": "https://www.linguee.pt/portugues-bulgaro",
    "PT-CS": "https://www.linguee.pt/portugues-checo",
    "PT-DA": "https://www.linguee.pt/portugues-dinamarques",
    "PT-DE": "https://www.linguee.pt/portugues-alemao",
    "PT-EL": "https://www.linguee.pt/portugues-grego",
    "PT-EN": "https://www.linguee.com/portuguese-english",
    "PT-ES": "https://www.linguee.pt/portugues-espanhol",
    "PT-ET": "https://www.linguee.pt/portugues-estonio",
    "PT-FI": "https://www.linguee.pt/portugues-finlandes",
    "PT-FR": "https://www.linguee.pt/portugues-frances",
    "PT-HU": "https://www.linguee.pt/portugues-hungaro",
    "PT-IT": "https://www.linguee.pt/portugues-italiano",
    "PT-LT": "https://www.linguee.pt/portugues-lituano",
    "PT-LV": "https://www.linguee.pt/portugues-letao",
    "PT-MT": "https://www.linguee.pt/portugues-maltes",
    "PT-NL": "https://www.linguee.pt/portugues-holandes",
    "PT-PL": "https://www.linguee.pt/portugues-polones",
    "PT-RO": "https://www.linguee.pt/portugues-romeno",
    "PT-SK": "https://www.linguee.pt/portugues-eslovaco",
    "PT-SL": "https://www.linguee.pt/portugues-esloveno",
    "PT-SV": "https://www.linguee.pt/portugues-sueco",
    "RO-BG": "https://ro.linguee.com/rom%C3%A2n%C4%83-bulgar%C4%83",
    "RO-CS": "https://ro.linguee.com/rom%C3%A2n%C4%83-ceh%C4%83",
    "RO-DA": "https://ro.linguee.com/rom%C3%A2n%C4%83-danez%C4%83",
    "RO-DE": "https://ro.linguee.com/rom%C3%A2n%C4%83-german%C4%83",
    "RO-EL": "https://ro.linguee.com/rom%C3%A2n%C4%83-greac%C4%83",
    "RO-EN": "https://www.linguee.com/romanian-english",
    "RO-ES": "https://ro.linguee.com/rom%C3%A2n%C4%83-spaniol%C4%83",
    "RO-ET": "https://ro.linguee.com/rom%C3%A2n%C4%83-eston%C4%83",
    "RO-FI": "https://ro.linguee.com/rom%C3%A2n%C4%83-finlandez%C4%83",
    "RO-FR": "https://ro.linguee.com/rom%C3%A2n%C4%83-francez%C4%83",
    "RO-HU": "https://ro.linguee.com/rom%C3%A2n%C4%83-maghiar%C4%83",
    "RO-IT": "https://ro.linguee.com/rom%C3%A2n%C4%83-italian%C4%83",
    "RO-LT": "https://ro.linguee.com/rom%C3%A2n%C4%83-lituanian%C4%83",
    "RO-LV": "https://ro.linguee.com/rom%C3%A2n%C4%83-leton%C4%83",
    "RO-MT": "https://ro.linguee.com/rom%C3%A2n%C4%83-maltez%C4%83",
    "RO-NL": "https://ro.linguee.com/rom%C3%A2n%C4%83-olandez%C4%83",
    "RO-PL": "https://ro.linguee.com/rom%C3%A2n%C4%83-polonez%C4%83",
    "RO-PT": "https://ro.linguee.com/rom%C3%A2n%C4%83-portughez%C4%83",
    "RO-SK": "https://ro.linguee.com/rom%C3%A2n%C4%83-slovac%C4%83",
    "RO-SL": "https://ro.linguee.com/rom%C3%A2n%C4%83-sloven%C4%83",
    "RO-SV": "https://ro.linguee.com/rom%C3%A2n%C4%83-suedez%C4%83",
    "RU-EN": "https://www.linguee.com/russian-english",
    "SK-BG": "https://sk.linguee.com/slovensk%C3%BD-bulharsk%C3%BD",
    "SK-CS": "https://sk.linguee.com/slovensk%C3%BD-%C4%8Desk%C3%BD",
    "SK-DA": "https://sk.linguee.com/slovensk%C3%BD-d%C3%A1nsky",
    "SK-DE": "https://sk.linguee.com/slovensk%C3%BD-nemeck%C3%BD",
    "SK-EL": "https://sk.linguee.com/slovensk%C3%BD-gr%C3%A9cky",
    "SK-EN": "https://www.linguee.com/slovak-english",
    "SK-ES": "https://sk.linguee.com/slovensk%C3%BD-%C5%A1panielsky",
    "SK-ET": "https://sk.linguee.com/slovensk%C3%BD-est%C3%B3nsky",
    "SK-FI": "https://sk.linguee.com/slovensk%C3%BD-f%C3%ADnsky",
    "SK-FR": "https://sk.linguee.com/slovensk%C3%BD-franc%C3%BAzsky",
    "SK-HU": "https://sk.linguee.com/slovensk%C3%BD-ma%C4%8Farsk%C3%BD",
    "SK-IT": "https://sk.linguee.com/slovensk%C3%BD-taliansky",
    "SK-LT": "https://sk.linguee.com/slovensk%C3%BD-litovsk%C3%BD",
    "SK-LV": "https://sk.linguee.com/slovensk%C3%BD-loty%C5%A1sk%C3%BD",
    "SK-MT": "https://sk.linguee.com/slovensk%C3%BD-maltsk%C3%BD",
    "SK-NL": "https://sk.linguee.com/slovensk%C3%BD-holandsk%C3%BD",
    "SK-PL": "https://sk.linguee.com/slovensk%C3%BD-po%C4%BEsk%C3%BD",
    "SK-PT": "https://sk.linguee.com/slovensk%C3%BD-portugalsk%C3%BD",
    "SK-RO": "https://sk.linguee.com/slovensk%C3%BD-rumunsk%C3%BD",
    "SK-SL": "https://sk.linguee.com/slovensk%C3%BD-slovinsk%C3%BD",
    "SK-SV": "https://sk.linguee.com/slovensk%C3%BD-%C5%A1v%C3%A9dsky",
    "SL-BG": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-bolgar%C5%A1%C4%8Dina",
    "SL-CS": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-%C4%8De%C5%A1%C4%8Dina",
    "SL-DA": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-dan%C5%A1%C4%8Dina",
    "SL-DE": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-nem%C5%A1%C4%8Dina",
    "SL-EL": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-gr%C5%A1%C4%8Dina",
    "SL-EN": "https://www.linguee.com/slovene-english",
    "SL-ES": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-%C5%A1pan%C5%A1%C4%8Dina",
    "SL-ET": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-eston%C5%A1%C4%8Dina",
    "SL-FI": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-fin%C5%A1%C4%8Dina",
    "SL-FR": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-franco%C5%A1%C4%8Dina",
    "SL-HU": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-mad%C5%BEar%C5%A1%C4%8Dina",
    "SL-IT": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-italijan%C5%A1%C4%8Dina",
    "SL-LT": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-litov%C5%A1%C4%8Dina",
    "SL-LV": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-latvij%C5%A1%C4%8Dina",
    "SL-MT": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-malte%C5%A1%C4%8Dina",
    "SL-NL": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-nizozem%C5%A1%C4%8Dina",
    "SL-PL": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-polj%C5%A1%C4%8Dina",
    "SL-PT": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-portugal%C5%A1%C4%8Dina",
    "SL-RO": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-romun%C5%A1%C4%8Dina",
    "SL-SK": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-slova%C5%A1%C4%8Dina",
    "SL-SV": "https://sl.linguee.com/sloven%C5%A1%C4%8Dina-%C5%A1ved%C5%A1%C4%8Dina",
    "SV-BG": "https://www.linguee.se/svensk-bulgarisk",
    "SV-CS": "https://www.linguee.se/svensk-tjeckisk",
    "SV-DA": "https://www.linguee.se/svensk-dansk",
    "SV-DE": "https://www.linguee.se/svensk-tysk",
    "SV-EL": "https://www.linguee.se/svensk-grekisk",
    "SV-EN": "https://www.linguee.com/swedish-english",
    "SV-ES": "https://www.linguee.se/svensk-spansk",
    "SV-ET": "https://www.linguee.se/svensk-estnisk",
    "SV-FI": "https://www.linguee.se/svensk-finsk",
    "SV-FR": "https://www.linguee.se/svensk-fransk",
    "SV-HU": "https://www.linguee.se/svensk-ungersk",
    "SV-IT": "https://www.linguee.se/svensk-italiensk",
    "SV-LT": "https://www.linguee.se/svensk-litauisk",
    "SV-LV": "https://www.linguee.se/svensk-lettisk",
    "SV-MT": "https://www.linguee.se/svensk-maltesisk",
    "SV-NL": "https://www.linguee.se/svensk-holl%C3%A4ndsk",
    "SV-PL": "https://www.linguee.se/svensk-polsk",
    "SV-PT": "https://www.linguee.se/svensk-portugisisk",
    "SV-RO": "https://www.linguee.se/svensk-rum%C3%A4nsk",
    "SV-SK": "https://www.linguee.se/svensk-slovakisk",
    "SV-SL": "https://www.linguee.se/svensk-slovensk",
    "ZH-EN": "https://www.linguee.com/chinese-english",
}
